/* Number of total columns/semesters: */
window.semesters = 10;

// Order of courses matters: do not swap positions. Append at the end.
window.courses = [
    { name: "Algoritmos e Programação", credits: 5, semester: 1},
    { name: "Int. a Eng. Comp. e Informação", credits: 2, semester: 1},
    { name: "Circuitos Lógicos", credits: 5, semester: 1},
    { name: "Cálculo I", credits: 6, semester: 1},
    { name: "Física I", credits: 4, semester: 1},
    { name: "Física Experimental I", credits: 1, semester: 1},
    { name: "Linguagens de Programação", credits: 5, semester: 2},
    { name: "Álgebra Linear II", credits: 4, semester: 2},
    { name: "Sistemas Digitais", credits: 5, semester: 2},
    { name: "Cálculo II", credits: 4, semester: 2},
    { name: "Física II", credits: 4, semester: 2},
    { name: "Física Experimental II", credits: 1, semester: 2},
    { name: "Atividades Acad. Opt. Humanas", credits: 2, semester: 2},
    { name: "Estrutura de Dados", credits: 5, semester: 3},
    { name: "Teoria da Computação", credits: 4, semester: 3},
    { name: "Arquitetura de Computadores", credits: 5, semester: 3},
    { name: "Cálculo III", credits: 4, semester: 3},
    { name: "Física III", credits: 4, semester: 3},
    { name: "Física Experimental III", credits: 1, semester: 3},
    { name: "Atividades Acad. Opt. Humanas", credits: 2, semester: 3},
    { name: "Teoria dos Grafos", credits: 4, semester: 4},
    { name: "Estatística e Mod. Probabilísticos", credits: 4, semester: 4},
    { name: "Computadores e Sociedade", credits: 4, semester: 4},
    { name: "Cálculo IV", credits: 4, semester: 4},
    { name: "Física IV", credits: 4, semester: 4},
    { name: "Física Experimental IV", credits: 1, semester: 4},
    { name: "Banco de Dados", credits: 4, semester: 5},
    { name: "Lógica Matemática", credits: 4, semester: 5},
    { name: "Álg. Linear Computacional", credits: 4, semester: 5},
    { name: "Redes de Computadores I", credits: 4, semester: 5},
    { name: "Sistemas Operacionais", credits: 5, semester: 5},
    { name: "Química Experimental", credits: 2, semester: 5},
    { name: "Otimização", credits: 4, semester: 6},
    { name: "Inteligência Computacional", credits: 4, semester: 6},
    { name: "Engenharia de Software", credits: 4, semester: 6},
    { name: "Redes de Computadores II", credits: 4, semester: 6},
    { name: "Telecomunic.", credits: 4, semester: 6},
    { name: "Computação Gráfica", credits: 4, semester: 6},
    { name: "Programação Avançada", credits: 4, semester: 7},
    { name: "Computação de Alto Desempenho", credits: 3, semester: 7},
    { name: "Sistemas Distribuídos", credits: 4, semester: 7},
    { name: "Gestão do Conhecimento", credits: 4, semester: 7},
    { name: "Atividades Acad. Optativas", credits: 8, semester: 7, step: 2},
    { name: "Construção de Banco de Dados", credits: 4, semester: 8},
    { name: "Empreend. I", credits: 4, semester: 8},
    { name: "Qualidade de Software", credits: 4, semester: 8},
    { name: "Projeto de Graduação", credits: 4, semester: 8},
    { name: "Atividades Acad. Optativas", credits: 8, semester: 8, step: 2},
    { name: "Estágio Obrigatório", credits: 160, semester: 9},
    { name: "Atividades Acad. Optativas", credits: 16, semester: 9, step: 2},
    { name: "Atividades Acad. Optativas", credits: 8, semester: 10, step: 2},
    { name: "Atividades Acad. Livre Escolha", credits: 8, semester: 10, step: 2},
    { name: "Ativ. Compl. Especiais", credits: 405, semester: 10, step: 15}
]
